version: '3'
services:
  hongo:
    restart: always
    image: fw-demo:v6
    stdin_open: true
    tty: true
    container_name: hongo
    environment:
      - REGION=hongo
      - MADDR=10001
      - PADDR=12001
      - NSNAME=vsix-hongo
    privileged: true
    user: "0:0"
    network_mode: host
    volumes:
      - /home/ito/.kube/config:/root/.kube/config
      - /var/run:/var/run
      - /run/netns:/run/netns
  komatsu:
    restart: always
    image: fw-demo:v6
    stdin_open: true
    tty: true
    container_name: komatsu
    environment:
      - REGION=komatsu
      - MADDR=10002
      - PADDR=12002
      - NSNAME=vsix-komatsu
    privileged: true
    user: "0:0"
    network_mode: host
    volumes:
      - /home/ito/.kube/config:/root/.kube/config
      - /var/run:/var/run
      - /run/netns:/run/netns
networks:
  default:
    name: kind
    external: true
