# permissions for end users to edit fwlets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fwlet-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fw-controller
    app.kubernetes.io/part-of: fw-controller
    app.kubernetes.io/managed-by: kustomize
  name: fwlet-editor-role
rules:
- apiGroups:
  - samplecontroller.yossy.vsix.wide.ad.jp
  resources:
  - fwlets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samplecontroller.yossy.vsix.wide.ad.jp
  resources:
  - fwlets/status
  verbs:
  - get
