# permissions for end users to edit fwprefixlists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fwprefixlist-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fw-controller
    app.kubernetes.io/part-of: fw-controller
    app.kubernetes.io/managed-by: kustomize
  name: fwprefixlist-editor-role
rules:
- apiGroups:
  - vsix.wide.ad.jp
  resources:
  - fwprefixlists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vsix.wide.ad.jp
  resources:
  - fwprefixlists/status
  verbs:
  - get
