---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - vsix.wide.ad.jp
  resources:
  - fwrouters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vsix.wide.ad.jp
  resources:
  - fwrouters/finalizers
  verbs:
  - update
- apiGroups:
  - vsix.wide.ad.jp
  resources:
  - fwrouters/status
  verbs:
  - get
  - patch
  - update
